version: '3'
services:

  mysql_server:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_USER=abc
      - MYSQL_DATABASE=test_db
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    # ports:
    #   - '3306:3306'
    # expose:
    #   - '3306'
    volumes:
      - /var/lib/mysql

    # networks:
    #   - internalnet

  apildata:
    container_name: nodev6
    build:
      context: ./Api/user-service
      dockerfile: Dockerfile
    # depends_on:
    #   - mysql_server
    image: node6:v6
    ports:
      - "4000:4000"
    expose:
      - 4000
    volumes:
      - ./Api/user-service:/app
    # networks:
    #   - internalnet

  # client:
  #   stdin_open: true
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - mysql_server
  #   volumes:
  #     - ./web:/app
  #    expose:
  #     - 4000
  #   networks:
  #     - internalnet

networks:
  internalnet:
    driver: bridge
