const SAVE_FORM_REQUEST = "SAVE_FORM_REQUEST";
const SAVE_FORM_IN_PROGRESS = "SAVE_FORM_IN_PROGRESS";
const SAVE_FORM_SUCCESS = "SAVE_FORM_SUCCESS";
const SAVE_FORM_FAILED = "SAVE_FORM_FAILED";

export  {
    SAVE_FORM_REQUEST,
    SAVE_FORM_IN_PROGRESS,
    SAVE_FORM_SUCCESS,
    SAVE_FORM_FAILED,
};
