# version: '3'

# x-common-variables: &common-variables
#   MYSQL_DATABASE: new_schema
#   MYSQL_PASSWORD: admin123

  
# services:
#   mysql_db2:
#     image: mysql
#     cap_add:
#       - SYS_NICE
#     volumes:
#       - $HOME/database:/var/lib/mysql
#       - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
#     ports:
#       - 3306:3306
#     expose:
#       - 3306
#     environment:
#      - MYSQL_DATABASE=new_schema
#      - MYSQL_PASSWORD=admin123
#      - MYSQL_ROOT_PASSWORD=admin123
#      - MYSQL_HOST=localhost
#     ports:
#       - "9906:3306"
#     networks:
#      - internalnet
#   back:
#     container_name: reshedule
#     build: .
#     image: node:v1
#     depends_on:
#       - mysql_db2
#     image: server
#     volumes:
#       - .:./app
#       - /app/node_modules
#     environment:
#      - MYSQL_DATABASE=new_schema
#      - MYSQL_PASSWORD=admin123
#      - MYSQL_ROOT_PASSWORD=admin123
#      - MYSQL_HOST=localhost

# networks:
#   internalnet:
#     driver: bridge    
     

    
   

 